CREATE TABLE GUEST (
    SABUN NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30), --UTF-8 : 숫자, 영문, 특수문자(키보드 상의기호 : 1 BYTE, 한글 : 3 BYTE)
    NALJA DATE,
    PAY NUMBER(20)
);

INSERT INTO GUEST VALUES (1111, 'USER-1', SYSDATE -2, 1000);
INSERT INTO GUEST VALUES (2222, 'USER-2', SYSDATE -1, 1000);
INSERT INTO GUEST (SABUN, NAME, PAY) VALUES(3333,'USER-3',3000);
UPDATE GUEST
    SET NALJA = SYSDATE
    WHERE SABUN = 3333;
    
DELETE FROM GUEST WHERE SABUN = 3333;
SELECT * FROM GUEST;
COMMIT;