CREATE TABLE MEMBER_T (
	ID VARCHAR2(20) PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(50)
);

INSERT INTO MEMBER_T 
       (ID, NAME, PASSWORD, EMAIL)
VALUES ('hong', '홍길동', 'hong1234', 'hong@test.com'); 
INSERT INTO MEMBER_T 
       (ID, NAME, PASSWORD, EMAIL)
VALUES ('kim', '김유신', 'kim1234', 'kim@test.com');

COMMIT;
